# Generated by Django 4.2.5 on 2023-09-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('responsavel', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('Gasto', 'Gasto'), ('Receita', 'Receita')], max_length=7)),
                ('valor', models.IntegerField()),
            ],
        ),
    ]
