# Generated by Django 4.2.5 on 2023-09-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cadastro_comprovante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('tipo_consulta', models.CharField(choices=[('consulta', 'consulta'), ('reclamacao', 'reclamação'), ('sugestao', 'sugestão'), ('felicitacoes', 'felicitações'), ('outro', 'outro')], max_length=12)),
                ('mensagem', models.TextField()),
            ],
        ),
    ]
